name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # Alternative for testing on multiple platforms. Ubuntu runs the quickest with the latest JVM.
        #   os: [ubuntu-latest, windows-latest, macos-latest]
        #   java-version: [11, 17]
        os: [ ubuntu-latest ]
        java-version: [ 17 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt-hotspot
          java-version: ${{ matrix.java-version }}
      
      # Run tests & build artifact
      - run: ./mvnw package
      
      # Upload test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: Event File
          retention-days: 21
          path: |
            **/TEST-*
            **/hs_err_pid*
            
      # Set JReleaser version: "var_to_set=$(command_to_run)" >> sink
      - run: echo "JRELEASER_PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      
      # Make release with JReleaser
      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Upload JRelease debug log
      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties